# Generated by Django 2.1.7 on 2019-02-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('url', models.URLField(max_length=300, verbose_name='Link')),
            ],
        ),
    ]
